---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-b31536c3
  image_type: c1.medium
  image_id: ami-d726abbe
  security_groups:
  - wellbe_production_default
  - wellbe_production_web
  - wellbe_production_web_tools
  - wellbe_production_production
  - wellbe_production_apache
  - wellbe_production_app
  - wellbe_production_passenger
  - wellbe_production_collectd
  - wellbe_production_common
  - wellbe_production_monit
  - wellbe_production_db
  - wellbe_production_postgresql
  - wellbe_production_postgresql_master
  - wellbe_production_elasticsearch
  - wellbe_production_examples
  - wellbe_production_graphite_server
  - wellbe_production_graphite_web
  - wellbe_production_graylog_elasticsearch
  - wellbe_production_graylog_mongodb
  - wellbe_production_mongodb
  - wellbe_production_graylog_server
  - wellbe_production_graylog_web
  - wellbe_production_haproxy
  external_host: ec2-54-234-204-165.compute-1.amazonaws.com
  external_ip: 54.234.204.165
  internal_host: ip-10-145-164-176.ec2.internal
  internal_ip: 10.145.164.176
  zone: us-east-1b
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: prod
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-55d5fa25
  image_type: c1.medium
  image_id: ami-d726abbe
  security_groups:
  - wellbe_production_default
  - wellbe_production_web
  - wellbe_production_web_tools
  - wellbe_production_prod
  - wellbe_production_apache
  - wellbe_production_app
  - wellbe_production_passenger
  - wellbe_production_collectd
  - wellbe_production_common
  - wellbe_production_monit
  - wellbe_production_db
  - wellbe_production_postgresql
  - wellbe_production_postgresql_master
  - wellbe_production_elasticsearch
  - wellbe_production_examples
  - wellbe_production_graphite_server
  - wellbe_production_graphite_web
  - wellbe_production_graylog_elasticsearch
  - wellbe_production_graylog_mongodb
  - wellbe_production_mongodb
  - wellbe_production_graylog_server
  - wellbe_production_graylog_web
  - wellbe_production_haproxy
  external_host: ec2-50-19-201-87.compute-1.amazonaws.com
  external_ip: 50.19.201.87
  internal_host: ip-10-244-115-77.ec2.internal
  internal_ip: 10.244.115.77
  zone: us-east-1b
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: product
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-35d2fd45
  image_type: c1.medium
  image_id: ami-d726abbe
  security_groups:
  - wellbe_production_default
  - wellbe_production_web
  - wellbe_production_web_tools
  - wellbe_production_product
  - wellbe_production_apache
  - wellbe_production_app
  - wellbe_production_passenger
  - wellbe_production_collectd
  - wellbe_production_common
  - wellbe_production_monit
  - wellbe_production_db
  - wellbe_production_postgresql
  - wellbe_production_postgresql_master
  - wellbe_production_elasticsearch
  - wellbe_production_examples
  - wellbe_production_graphite_server
  - wellbe_production_graphite_web
  - wellbe_production_graylog_elasticsearch
  - wellbe_production_graylog_mongodb
  - wellbe_production_mongodb
  - wellbe_production_graylog_server
  - wellbe_production_graylog_web
  - wellbe_production_haproxy
  external_host: ec2-50-19-162-181.compute-1.amazonaws.com
  external_ip: 50.19.162.181
  internal_host: ip-10-38-193-148.ec2.internal
  internal_ip: 10.38.193.148
  zone: us-east-1b
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: wellbe
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-a1be91d1
  image_type: c1.medium
  image_id: ami-d726abbe
  security_groups:
  - wellbe_production_default
  - wellbe_production_web
  - wellbe_production_web_tools
  - wellbe_production_wellbe
  - wellbe_production_apache
  - wellbe_production_app
  - wellbe_production_passenger
  - wellbe_production_collectd
  - wellbe_production_common
  - wellbe_production_monit
  - wellbe_production_db
  - wellbe_production_postgresql
  - wellbe_production_postgresql_master
  - wellbe_production_elasticsearch
  - wellbe_production_examples
  - wellbe_production_graphite_server
  - wellbe_production_graphite_web
  - wellbe_production_graylog_elasticsearch
  - wellbe_production_graylog_mongodb
  - wellbe_production_mongodb
  - wellbe_production_graylog_server
  - wellbe_production_graylog_web
  - wellbe_production_haproxy
  external_host: ec2-107-20-50-81.compute-1.amazonaws.com
  external_ip: 107.20.50.81
  internal_host: ip-10-112-251-159.ec2.internal
  internal_ip: 10.112.251.159
  zone: us-east-1b
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-97b897e7
  image_type: c1.medium
  image_id: ami-d726abbe
  security_groups:
  - wellbe_production_default
  - wellbe_production_db
  - wellbe_production_postgresql
  - wellbe_production_postgresql_master
  - wellbe_production_collectd
  - wellbe_production_monit
  external_host: ec2-67-202-24-153.compute-1.amazonaws.com
  external_ip: 67.202.24.153
  internal_host: ip-10-194-197-51.ec2.internal
  internal_ip: 10.194.197.51
  zone: us-east-1b
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
